import { motion } from "framer-motion";
import {
  FaRobot,
  FaFileAlt,
  FaBullseye,
  FaRoute,
  FaComments,
  FaChartLine,
} from "react-icons/fa";

const features = [
  {
    icon: <FaRobot />,
    title: "AI Semantic Matching",
    description:
      "Compares your resume with job descriptions using AI to understand skills beyond keywords.",
  },
  {
    icon: <FaFileAlt />,
    title: "ATS Score Analysis",
    description:
      "Evaluate how well your resume performs against Applicant Tracking Systems.",
  },
  {
    icon: <FaBullseye />,
    title: "Skill Gap Detection",
    description:
      "Identify missing technical and soft skills required for your dream role.",
  },
  {
    icon: <FaRoute />,
    title: "Learning Roadmap",
    description:
      "Receive a personalized week-by-week learning plan generated by AI.",
  },
  {
    icon: <FaComments />,
    title: "Interview Preparation",
    description:
      "Get role-specific interview questions to practice before applying.",
  },
  {
    icon: <FaChartLine />,
    title: "Smart Analytics",
    description:
      "Track resume quality, semantic match, keyword match, and ATS performance in one dashboard.",
  },
];

export default function Features() {
  return (
    <div className="py-12">
      {/* Heading */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="text-center max-w-xl mx-auto mb-10"
      >
        <span className="inline-flex items-center gap-1 rounded-md border border-indigo-500/30 bg-indigo-500/10 px-3 py-1 text-xs font-bold text-indigo-300">
          Core Capabilities
        </span>

        <h2 className="mt-3 text-2xl font-black tracking-tight text-white sm:text-3xl">
          Everything Needed for ATS & Recruiter Success
        </h2>

        <p className="mt-2 text-xs text-slate-400">
          State-of-the-art vector embedding match algorithms, automated formatting audits, and Groq-powered career copilot.
        </p>
      </motion.div>

      {/* Cards Grid */}
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        {features.map((feature, index) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 25 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: index * 0.08 }}
            className="group rounded-2xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl backdrop-blur-md card-hover-effect cursor-pointer"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 mb-4 transition-transform duration-300 group-hover:scale-110 group-hover:bg-indigo-500/20">
              {feature.icon}
            </div>

            <h3 className="text-base font-bold text-white transition-colors group-hover:text-indigo-300">
              {feature.title}
            </h3>

            <p className="mt-2 text-xs leading-relaxed text-slate-400">
              {feature.description}
            </p>
          </motion.div>
        ))}
      </div>
    </div>
  );
}