import { motion } from "framer-motion";
import {
  FaRobot,
  FaFileAlt,
  FaBullseye,
  FaRoute,
  FaComments,
  FaChartLine,
} from "react-icons/fa";

const features = [
  {
    icon: <FaRobot />,
    title: "AI Semantic Matching",
    description:
      "Compares your resume with job descriptions using AI to understand skills beyond keywords.",
    color: "from-emerald-400 to-teal-500",
  },
  {
    icon: <FaFileAlt />,
    title: "ATS Score Analysis",
    description:
      "Evaluate how well your resume performs against Applicant Tracking Systems.",
    color: "from-teal-400 to-cyan-500",
  },
  {
    icon: <FaBullseye />,
    title: "Skill Gap Detection",
    description:
      "Identify missing technical and soft skills required for your dream role.",
    color: "from-cyan-400 to-emerald-500",
  },
  {
    icon: <FaRoute />,
    title: "Learning Roadmap",
    description:
      "Receive a personalized week-by-week learning plan generated by AI.",
    color: "from-amber-400 to-emerald-500",
  },
  {
    icon: <FaComments />,
    title: "Interview Preparation",
    description:
      "Get role-specific interview questions to practice before applying.",
    color: "from-emerald-400 to-teal-500",
  },
  {
    icon: <FaChartLine />,
    title: "Smart Analytics",
    description:
      "Track resume quality, semantic match, keyword match, and ATS performance in one dashboard.",
    color: "from-teal-400 to-cyan-500",
  },
];

export default function Features() {
  return (
    <section className="py-24">
      {/* Heading */}

      <motion.div
        initial={{ opacity: 0, y: 25 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        viewport={{ once: true }}
        className="text-center"
      >
        <span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-sm font-semibold text-emerald-300">
          Why Choose ResumeMatch AI?
        </span>

        <h2 className="mx-auto mt-6 max-w-3xl font-display text-4xl font-bold text-foreground text-balance lg:text-5xl">
          Everything you need to get{" "}
          <span className="bg-gradient-to-r from-emerald-400 to-teal-300 bg-clip-text text-transparent">
            hired faster
          </span>
        </h2>

        <p className="mx-auto mt-5 max-w-2xl text-lg text-muted-foreground text-pretty">
          Optimize your resume, improve ATS compatibility, identify skill gaps,
          and prepare confidently for your next opportunity.
        </p>
      </motion.div>

      {/* Cards */}

      <div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {features.map((feature, index) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.45, delay: index * 0.08 }}
            viewport={{ once: true }}
            whileHover={{ y: -8 }}
            className="group relative overflow-hidden rounded-3xl border border-border bg-card p-8 shadow-sm transition-all duration-300 hover:border-emerald-400/40 hover:shadow-2xl hover:shadow-emerald-500/10"
          >
            <div
              className={`flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br ${feature.color} text-2xl text-primary-foreground shadow-lg transition-transform duration-300 group-hover:scale-110`}
            >
              {feature.icon}
            </div>

            <h3 className="mt-6 font-display text-2xl font-bold text-foreground">
              {feature.title}
            </h3>

            <p className="mt-4 leading-7 text-muted-foreground">
              {feature.description}
            </p>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
