import { motion } from "framer-motion";
import {
  FaRobot,
  FaFileAlt,
  FaBullseye,
  FaRoute,
  FaComments,
  FaChartLine,
} from "react-icons/fa";

const features = [
  {
    icon: <FaRobot />,
    title: "AI Semantic Matching",
    description:
      "Compares your resume with job descriptions using AI to understand skills beyond keywords.",
  },
  {
    icon: <FaFileAlt />,
    title: "ATS Score Analysis",
    description:
      "Evaluate how well your resume performs against Applicant Tracking Systems.",
  },
  {
    icon: <FaBullseye />,
    title: "Skill Gap Detection",
    description:
      "Identify missing technical and soft skills required for your dream role.",
  },
  {
    icon: <FaRoute />,
    title: "Learning Roadmap",
    description:
      "Receive a personalized week-by-week learning plan generated by AI.",
  },
  {
    icon: <FaComments />,
    title: "Interview Preparation",
    description:
      "Get role-specific interview questions to practice before applying.",
  },
  {
    icon: <FaChartLine />,
    title: "Smart Analytics",
    description:
      "Track resume quality, semantic match, keyword match, and ATS performance in one dashboard.",
  },
];

export default function Features() {
  return (
    <section className="py-24">
      {/* Heading */}

      <motion.div
        initial={{ opacity: 0, y: 25 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        viewport={{ once: true }}
        className="text-center"
      >
        <span className="rounded-full bg-blue-100 px-4 py-2 text-sm font-semibold text-blue-700">
          Why Choose ResumeMatch AI?
        </span>

        <h2 className="mt-6 text-5xl font-bold text-slate-900">
          Powerful AI Features
        </h2>

        <p className="mx-auto mt-5 max-w-2xl text-lg text-slate-600">
          Everything you need to optimize your resume, improve ATS compatibility,
          identify skill gaps, and prepare confidently for your next opportunity.
        </p>
      </motion.div>

      {/* Cards */}

      <div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        {features.map((feature, index) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{
              duration: 0.45,
              delay: index * 0.1,
            }}
            viewport={{ once: true }}
            whileHover={{
              y: -8,
            }}
            className="group rounded-3xl border border-slate-200 bg-white p-8 shadow-sm transition-all duration-300 hover:shadow-2xl"
          >
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 text-2xl text-white shadow-lg transition-transform duration-300 group-hover:scale-110">
              {feature.icon}
            </div>

            <h3 className="mt-6 text-2xl font-bold text-slate-900">
              {feature.title}
            </h3>

            <p className="mt-4 leading-7 text-slate-600">
              {feature.description}
            </p>
          </motion.div>
        ))}
      </div>
    </section>
  );
}