import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
} from "docx";
import { saveAs } from "file-saver";

export const downloadDOCX = async (title, content) => {
  // Split content into paragraphs
  const paragraphs = content
    .split("\n")
    .filter((line) => line.trim() !== "")
    .map(
      (line) =>
        new Paragraph({
          children: [
            new TextRun({
              text: line,
              size: 24, // 12pt
            }),
          ],
          spacing: {
            after: 200,
          },
        })
    );

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
              new TextRun({
                text: title,
                bold: true,
                size: 32,
              }),
            ],
            spacing: {
              after: 300,
            },
          }),

          ...paragraphs,

          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by ResumeMatchAI • ${new Date().toLocaleDateString()}`,
                italics: true,
                color: "777777",
                size: 18,
              }),
            ],
            spacing: {
              before: 400,
            },
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);

  saveAs(blob, `${title.replace(/\s+/g, "_")}.docx`);
};