import jsPDF from "jspdf";

export const downloadPDF = (title, content) => {
  const doc = new jsPDF();

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, 20, 20);

  // Divider
  doc.setDrawColor(180);
  doc.line(20, 26, 190, 26);

  // Body
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  const lines = doc.splitTextToSize(content, 170);

  let y = 38;

  lines.forEach((line) => {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }

    doc.text(line, 20, y);
    y += 7;
  });

  // Footer
  const date = new Date().toLocaleDateString();

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    `Generated by ResumeMatchAI • ${date}`,
    20,
    290
  );

  doc.save(`${title.replace(/\s+/g, "_")}.pdf`);
};